databases:
  - name: api_dgii
    databaseName: api_dgii
    user: darlin

services:
  - type: web
    name: api_dgii
    runtime: python-3.10.6
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: darlin
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
