# Generated by Django 4.2.6 on 2023-11-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc', models.CharField(max_length=11, unique=True)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('actividad_economica', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('tipo_contribuyente', models.CharField(max_length=50)),
            ],
        ),
    ]
